-- ==============================================================================
-- Migration: 20260822000001_create_core_schema.sql
-- Description: Core schema definition for Solana Meme Coin Scanner (11 tables)
-- ==============================================================================

-- 1. WALLETS (Track deployers and flagged wallets)
CREATE TABLE IF NOT EXISTS public.wallets (
    wallet_address VARCHAR(64) PRIMARY KEY,
    first_seen TIMESTAMPTZ DEFAULT now(),
    reputation_score FLOAT8 DEFAULT 0.0,
    rug_count_history INT4 DEFAULT 0,
    total_tokens_launched INT4 DEFAULT 0,
    tags JSONB DEFAULT '[]'::jsonb
);

-- 2. TOKENS (Ingested tokens from Pump.fun and Raydium)
CREATE TABLE IF NOT EXISTS public.tokens (
    token_address VARCHAR(64) PRIMARY KEY,
    symbol VARCHAR(32),
    name VARCHAR(128),
    deployer_wallet_address VARCHAR(64) REFERENCES public.wallets(wallet_address) ON DELETE SET NULL,
    launch_timestamp TIMESTAMPTZ DEFAULT now(),
    launch_venue VARCHAR(32) NOT NULL,
    status VARCHAR(32) DEFAULT 'INGESTED'::character varying,
    initial_metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_tokens_launch_time ON public.tokens (launch_timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_tokens_status ON public.tokens (status);

-- 3. FILTER_RESULTS (Results from Hard Safety Filter & Instant Scalp Heuristics)
CREATE TABLE IF NOT EXISTS public.filter_results (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_address VARCHAR(64) NOT NULL REFERENCES public.tokens(token_address) ON DELETE CASCADE,
    checked_at TIMESTAMPTZ DEFAULT now(),
    mint_authority_renounced BOOLEAN DEFAULT false,
    freeze_authority_renounced BOOLEAN DEFAULT false,
    lp_locked_or_burned BOOLEAN DEFAULT false,
    lp_lock_pct FLOAT8 DEFAULT 0.0,
    top10_holder_pct FLOAT8 DEFAULT 0.0,
    honeypot_check_passed BOOLEAN DEFAULT true,
    dev_holding_pct FLOAT8 DEFAULT 0.0,
    sniper_bundle_pct FLOAT8 DEFAULT 0.0,
    instant_scalp_flags_count INT4 DEFAULT 0,
    filter_pass BOOLEAN NOT NULL,
    rejection_reason TEXT,
    raw_check_data JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_filter_results_token ON public.filter_results (token_address);

-- 4. WALLET_RELATIONSHIPS (2-Hop Funding Graph Connections)
CREATE TABLE IF NOT EXISTS public.wallet_relationships (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_a VARCHAR(64) NOT NULL,
    wallet_b VARCHAR(64) NOT NULL,
    relationship_type VARCHAR(64),
    hop_distance INT4 DEFAULT 1,
    detected_at TIMESTAMPTZ DEFAULT now(),
    shared_funding_sol FLOAT8 DEFAULT 0.0,
    confidence_score FLOAT8 DEFAULT 0.0
);

-- 5. METRIC_SNAPSHOTS (Time-series snapshot of market metrics & sub-scores)
CREATE TABLE IF NOT EXISTS public.metric_snapshots (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_address VARCHAR(64) NOT NULL REFERENCES public.tokens(token_address) ON DELETE CASCADE,
    snapshot_at TIMESTAMPTZ DEFAULT now(),
    market_cap_usd FLOAT8 DEFAULT 0.0,
    liquidity_usd FLOAT8 DEFAULT 0.0,
    volume_5m_usd FLOAT8 DEFAULT 0.0,
    buy_tx_count_5m INT4 DEFAULT 0,
    sell_tx_count_5m INT4 DEFAULT 0,
    net_buy_pressure_ratio FLOAT8 DEFAULT 0.0,
    global_priority_fees_sol FLOAT8 DEFAULT 0.0,
    bonding_curve_pct FLOAT8 DEFAULT 0.0,
    unique_holders_count INT4 DEFAULT 0,
    dexscreener_boosted BOOLEAN DEFAULT false,
    dexscreener_ads_active BOOLEAN DEFAULT false,
    opportunity_score FLOAT8 DEFAULT 0.0,
    score_vol_velocity FLOAT8,
    score_smart_money FLOAT8,
    score_global_fee FLOAT8,
    score_holder_curve FLOAT8,
    score_social_meta FLOAT8,
    weights_used JSONB DEFAULT '{}'::jsonb,
    active_components TEXT[] DEFAULT '{}'::text[],
    raw_metrics JSONB DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_metric_snapshots_token ON public.metric_snapshots (token_address);

-- 6. SMART_MONEY_PROFILES (High-profitability tracked wallets)
CREATE TABLE IF NOT EXISTS public.smart_money_profiles (
    wallet_address VARCHAR(64) PRIMARY KEY REFERENCES public.wallets(wallet_address) ON DELETE CASCADE,
    net_realized_profit_sol FLOAT8 DEFAULT 0.0,
    total_volume_sol FLOAT8 DEFAULT 0.0,
    total_trades_recorded INT4 DEFAULT 0,
    win_rate_pct FLOAT8 DEFAULT 0.0,
    profit_factor FLOAT8 DEFAULT 0.0,
    last_active_at TIMESTAMPTZ DEFAULT now(),
    is_active BOOLEAN DEFAULT true,
    tier VARCHAR(32) DEFAULT 'BRONZE'::character varying,
    source TEXT DEFAULT 'MANUAL'::text,
    notes TEXT DEFAULT ''::text,
    first_added TIMESTAMPTZ DEFAULT now()
);

-- 7. SMART_MONEY_TRADES (Trade log for tracked smart money wallets)
CREATE TABLE IF NOT EXISTS public.smart_money_trades (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_address VARCHAR(64) NOT NULL REFERENCES public.wallets(wallet_address) ON DELETE CASCADE,
    token_address VARCHAR(64) NOT NULL,
    trade_type VARCHAR(16) NOT NULL,
    amount_sol FLOAT8 DEFAULT 0.0,
    entry_price_usd FLOAT8 DEFAULT 0.0,
    exit_price_usd FLOAT8 DEFAULT 0.0,
    realized_pnl_sol FLOAT8 DEFAULT 0.0,
    executed_at TIMESTAMPTZ DEFAULT now()
);

-- 8. SIGNALS (Generated opportunity signals for Telegram delivery)
CREATE TABLE IF NOT EXISTS public.signals (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_address VARCHAR(64) NOT NULL REFERENCES public.tokens(token_address) ON DELETE CASCADE,
    generated_at TIMESTAMPTZ DEFAULT now(),
    total_opportunity_score FLOAT8 DEFAULT 0.0,
    volume_velocity_score FLOAT8 DEFAULT 0.0,
    smart_money_score FLOAT8 DEFAULT 0.0,
    global_fee_urgency_score FLOAT8 DEFAULT 0.0,
    holder_distribution_score FLOAT8 DEFAULT 0.0,
    social_meta_score FLOAT8 DEFAULT 0.0,
    two_stage_status VARCHAR(32) DEFAULT 'STAGE1_SENT'::character varying,
    fast_summary_text TEXT,
    llm_reasoning TEXT,
    layer_version VARCHAR(32) DEFAULT 'v1.0'::character varying
);

-- 9. OUTCOMES (Multi-timeframe resolution tracking: 5m, 15m, 1h, 4h, 24h)
CREATE TABLE IF NOT EXISTS public.outcomes (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_address VARCHAR(64) NOT NULL REFERENCES public.tokens(token_address) ON DELETE CASCADE,
    price_at_signal FLOAT8 DEFAULT 0.0,
    mcap_at_signal FLOAT8 DEFAULT 0.0,
    peak_5m FLOAT8 DEFAULT 0.0,
    peak_15m FLOAT8 DEFAULT 0.0,
    peak_1h FLOAT8 DEFAULT 0.0,
    peak_4h FLOAT8 DEFAULT 0.0,
    peak_24h FLOAT8 DEFAULT 0.0,
    max_multiplier_achieved FLOAT8 DEFAULT 0.0,
    max_drawdown_pct FLOAT8 DEFAULT 0.0,
    estimated_net_pnl_pct FLOAT8 DEFAULT 0.0,
    outcome_category VARCHAR(32) DEFAULT 'PENDING'::character varying,
    resolved_at TIMESTAMPTZ
);

-- 10. USERS (Telegram bot subscriber accounts)
CREATE TABLE IF NOT EXISTS public.users (
    telegram_user_id VARCHAR(64) PRIMARY KEY,
    username VARCHAR(128),
    joined_at TIMESTAMPTZ DEFAULT now(),
    role VARCHAR(32) DEFAULT 'USER'::character varying,
    notifications_enabled BOOLEAN DEFAULT true
);

-- 11. NOTIFICATIONS (Sent and updated Telegram notifications)
CREATE TABLE IF NOT EXISTS public.notifications (
    id INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_user_id VARCHAR(64) REFERENCES public.users(telegram_user_id) ON DELETE CASCADE,
    token_address VARCHAR(64) NOT NULL REFERENCES public.tokens(token_address) ON DELETE CASCADE,
    telegram_message_id INT8,
    notification_stage VARCHAR(32) DEFAULT 'STAGE_1'::character varying,
    sent_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ,
    message_content TEXT
);

-- Row Level Security (RLS) Configuration
ALTER TABLE public.wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tokens ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.filter_results ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallet_relationships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.metric_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.smart_money_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.smart_money_trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.signals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.outcomes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
