-- ==============================================================================
-- Migration: 20260831000001_create_smart_money_discovery.sql
-- Description: Smart Money Discovery pipeline tables
--              (separate from smart_money_profiles operational registry)
--
-- Tables:
--   1. smart_money_wallets  — Wallet profiles discovered by the pipeline
--   2. smart_money_hits     — Audit trail of every classified early buy event
-- ==============================================================================

-- 1. SMART_MONEY_WALLETS
-- Stores the result of the qualification pipeline per wallet.
-- Distinct from smart_money_profiles (the operational scoring registry).
CREATE TABLE IF NOT EXISTS public.smart_money_wallets (
    wallet_address       VARCHAR(64) PRIMARY KEY,
    sol_balance          FLOAT8      DEFAULT 0.0,
    runner_hit_count     INT4        DEFAULT 0,    -- Phase 2: runner tokens where wallet was early buyer
    dead_hit_count       INT4        DEFAULT 0,    -- Phase 3: dead tokens where wallet was also early
    neutral_hit_count    INT4        DEFAULT 0,    -- Phase 3: unclassifiable early buys (skipped)
    total_early_buys     INT4        DEFAULT 0,    -- runner_hit_count + dead_hit_count (classifiable only)
    hit_ratio            FLOAT8      DEFAULT 0.0,  -- runner_hit_count / total_early_buys
    status               VARCHAR(32) DEFAULT 'PENDING',  -- 'PENDING' | 'QUALIFIED' | 'REJECTED'
    rejection_reason     TEXT        DEFAULT '',   -- 'low_balance' | 'low_hits' | 'low_sample' | 'low_ratio'
    discovered_at        TIMESTAMPTZ DEFAULT now(),
    last_evaluated_at    TIMESTAMPTZ DEFAULT now(),
    notes                TEXT        DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_smw_status       ON public.smart_money_wallets (status);
CREATE INDEX IF NOT EXISTS idx_smw_discovered   ON public.smart_money_wallets (discovered_at DESC);
CREATE INDEX IF NOT EXISTS idx_smw_hit_ratio    ON public.smart_money_wallets (hit_ratio DESC);

-- 2. SMART_MONEY_HITS
-- Every classified early-buy event for every wallet we've ever analyzed.
-- Acts as the audit trail that powers negative control analysis.
CREATE TABLE IF NOT EXISTS public.smart_money_hits (
    id                   INT4        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_address       VARCHAR(64) NOT NULL,
    token_address        VARCHAR(64) NOT NULL,
    token_symbol         VARCHAR(32),
    token_label          VARCHAR(16) NOT NULL,     -- 'RUNNER' | 'DEAD' | 'NEUTRAL'
    source               VARCHAR(16) DEFAULT 'TRACE',  -- 'TRACE' = found via runner tracing
                                                       -- 'HISTORY' = found via wallet history scan
    buy_amount_sol       FLOAT8      DEFAULT 0.0,
    entry_time_seconds   INT4        DEFAULT 0,    -- seconds after token launch (early window)
    bought_at            TIMESTAMPTZ,
    entry_price_usd      FLOAT8      DEFAULT 0.0,  -- price at time of buy (derived from tx)
    current_price_usd    FLOAT8      DEFAULT 0.0,  -- price at time of classification (DexScreener)
    token_fdv_usd        FLOAT8      DEFAULT 0.0,  -- FDV from DexScreener at classification time
    UNIQUE (wallet_address, token_address)         -- one entry per wallet-token pair
);

CREATE INDEX IF NOT EXISTS idx_smh_wallet   ON public.smart_money_hits (wallet_address);
CREATE INDEX IF NOT EXISTS idx_smh_token    ON public.smart_money_hits (token_address);
CREATE INDEX IF NOT EXISTS idx_smh_label    ON public.smart_money_hits (token_label);
CREATE INDEX IF NOT EXISTS idx_smh_source   ON public.smart_money_hits (source);

-- RLS (consistent with other tables in this project)
ALTER TABLE public.smart_money_wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.smart_money_hits    ENABLE ROW LEVEL SECURITY;
